import type { GridTemplate } from "../types";

export const TEMPLATES: GridTemplate[] = [
  {
    id: "hero-cards",
    name: "Hero + Cards",
    description: "Large hero cell with supporting stat cards",
    config: { columns: 4, rows: 3, gap: 16, padding: 24 },
    cells: [
      {
        colStart: 1,
        rowStart: 1,
        colSpan: 2,
        rowSpan: 2,
        content: {
          type: "text",
          heading: "The Future is Here",
          subheading: "Product Launch 2025",
          body: "A revolutionary platform built for the next generation of creators and makers.",
          align: "left",
          headingSize: "xl",
        },
      },
      {
        colStart: 3,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Active Users",
          value: "48K",
          trend: "+24%",
          trendDirection: "up",
        },
      },
      {
        colStart: 4,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Revenue",
          value: "$1.2M",
          trend: "+18%",
          trendDirection: "up",
        },
      },
      {
        colStart: 3,
        rowStart: 2,
        colSpan: 2,
        rowSpan: 1,
        content: {
          type: "feature",
          icon: "🚀",
          title: "Ship Faster",
          description: "Deploy in seconds with zero-config pipelines.",
        },
      },
      {
        colStart: 1,
        rowStart: 3,
        colSpan: 4,
        rowSpan: 1,
        content: {
          type: "tagcloud",
          tags: ["Speed", "Scale", "Security", "Simplicity", "Open Source", "Cloud Native"],
        },
      },
    ],
  },
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Stats row with content below",
    config: { columns: 4, rows: 3, gap: 12, padding: 20 },
    cells: [
      {
        colStart: 1,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Total Sales",
          value: "$84,240",
          trend: "+12.5%",
          trendDirection: "up",
        },
      },
      {
        colStart: 2,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "New Users",
          value: "3,412",
          trend: "+6.1%",
          trendDirection: "up",
        },
      },
      {
        colStart: 3,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Bounce Rate",
          value: "24.8%",
          trend: "-3.2%",
          trendDirection: "down",
        },
      },
      {
        colStart: 4,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Avg Session",
          value: "4m 32s",
          trend: "+0.8%",
          trendDirection: "up",
        },
      },
      {
        colStart: 1,
        rowStart: 2,
        colSpan: 3,
        rowSpan: 2,
        content: {
          type: "image",
          src: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop",
          alt: "Analytics chart",
          fit: "cover",
          position: "center center",
        },
      },
      {
        colStart: 4,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 2,
        content: {
          type: "feature",
          icon: "📈",
          title: "Trending Up",
          description: "All key metrics are improving this quarter.",
        },
      },
    ],
  },
  {
    id: "feature-showcase",
    name: "Feature Showcase",
    description: "3-column feature grid with code snippet",
    config: { columns: 3, rows: 3, gap: 16, padding: 24 },
    cells: [
      {
        colStart: 1,
        rowStart: 1,
        colSpan: 3,
        rowSpan: 1,
        content: {
          type: "text",
          heading: "Built for Developers",
          subheading: "Powerful features, simple API",
          body: "",
          align: "center",
          headingSize: "2xl",
        },
      },
      {
        colStart: 1,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "feature",
          icon: "⚡",
          title: "Fast",
          description: "Sub-millisecond response times at any scale.",
        },
      },
      {
        colStart: 2,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "feature",
          icon: "🔒",
          title: "Secure",
          description: "End-to-end encryption and SOC2 compliance.",
        },
      },
      {
        colStart: 3,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "feature",
          icon: "🌍",
          title: "Global",
          description: "Edge network across 200+ locations worldwide.",
        },
      },
      {
        colStart: 1,
        rowStart: 3,
        colSpan: 2,
        rowSpan: 1,
        content: {
          type: "code",
          language: "ts",
          code: `import { client } from '@myapp/sdk';\n\nconst result = await client.run({\n  model: 'fast-v2',\n  input: { query: 'Hello!' },\n});`,
        },
      },
      {
        colStart: 3,
        rowStart: 3,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Uptime",
          value: "99.99%",
          trend: "365 days",
          trendDirection: "neutral",
        },
      },
    ],
  },
  {
    id: "minimal-2x2",
    name: "Minimal 2×2",
    description: "Four equal cells",
    config: { columns: 2, rows: 2, gap: 16, padding: 24 },
    cells: [
      {
        colStart: 1,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Revenue",
          value: "$42K",
          trend: "+15%",
          trendDirection: "up",
        },
      },
      {
        colStart: 2,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Users",
          value: "8,200",
          trend: "+9%",
          trendDirection: "up",
        },
      },
      {
        colStart: 1,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "feature",
          icon: "💡",
          title: "Insight",
          description: "Real-time analytics at a glance.",
        },
      },
      {
        colStart: 2,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: { type: "tagcloud", tags: ["Design", "Data", "Growth", "Product"] },
      },
    ],
  },
  {
    id: "portrait-hero",
    name: "Portrait Hero",
    description: "Tall image with flanking content",
    config: { columns: 3, rows: 3, gap: 16, padding: 24 },
    cells: [
      {
        colStart: 1,
        rowStart: 1,
        colSpan: 1,
        rowSpan: 3,
        content: {
          type: "image",
          src: "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=600&auto=format&fit=crop",
          alt: "Hero portrait",
          fit: "cover",
          position: "center top",
        },
      },
      {
        colStart: 2,
        rowStart: 1,
        colSpan: 2,
        rowSpan: 1,
        content: {
          type: "text",
          heading: "Designed to Delight",
          subheading: "Every pixel matters",
          body: "We obsess over the details so you can focus on what matters most — building great products.",
          align: "left",
          headingSize: "xl",
        },
      },
      {
        colStart: 2,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Happy Customers",
          value: "12K+",
          trend: "+200% YoY",
          trendDirection: "up",
        },
      },
      {
        colStart: 3,
        rowStart: 2,
        colSpan: 1,
        rowSpan: 1,
        content: {
          type: "stat",
          label: "Countries",
          value: "68",
          trend: "Worldwide",
          trendDirection: "neutral",
        },
      },
      {
        colStart: 2,
        rowStart: 3,
        colSpan: 2,
        rowSpan: 1,
        content: {
          type: "tagcloud",
          tags: ["UX", "Accessibility", "Performance", "Craft", "Open Source"],
        },
      },
    ],
  },
];
